# .nixpacks.toml
[phases.setup]
# Force Node 22; (nodejs_22 is the nixpkgs name)
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
# Add --configuration production if you have it
cmds = ["npm run build -- --configuration production"]

[start]
# Serve the built Angular app; adjust output path to your real dist folder
cmd = "npx serve -s dist/landing-design-pro -l ${PORT:-3000}"
